---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Configure Apache ports
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: Restart Apache2

- name: Configure Apache virtual host
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache2

- name: Deploy index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Deploy date page
  template:
    src: date.html.j2
    dest: /var/www/html/date.html
